### ISSUE TITLE
设置默认的水印配置信息

### ISSUE THREAD

**Issue by MOONCOM** [ZhuHuaijun/vue-watermark-directive#1]
建议可以在index.js初始化插件时，设置默认的水印参数，这样就可以不用在Vue.use()时传递所有的配置信息了

**Comment by FrankKai** [comment]
> 建议可以在index.js初始化插件时，设置默认的水印参数，这样就可以不用在Vue.use()时传递所有的配置信息了

在watermark.js中有默认配置。
